// Generated by gencpp from file main_program/startingResponse.msg
// DO NOT EDIT!


#ifndef MAIN_PROGRAM_MESSAGE_STARTINGRESPONSE_H
#define MAIN_PROGRAM_MESSAGE_STARTINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main_program
{
template <class ContainerAllocator>
struct startingResponse_
{
  typedef startingResponse_<ContainerAllocator> Type;

  startingResponse_()
    {
    }
  startingResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::main_program::startingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_program::startingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct startingResponse_

typedef ::main_program::startingResponse_<std::allocator<void> > startingResponse;

typedef boost::shared_ptr< ::main_program::startingResponse > startingResponsePtr;
typedef boost::shared_ptr< ::main_program::startingResponse const> startingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main_program::startingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main_program::startingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace main_program

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::main_program::startingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_program::startingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_program::startingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_program::startingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_program::startingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_program::startingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main_program::startingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::main_program::startingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::main_program::startingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main_program/startingResponse";
  }

  static const char* value(const ::main_program::startingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main_program::startingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::main_program::startingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main_program::startingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_program::startingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::main_program::startingResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_PROGRAM_MESSAGE_STARTINGRESPONSE_H
