// Generated by gencpp from file main_program/starting.msg
// DO NOT EDIT!


#ifndef MAIN_PROGRAM_MESSAGE_STARTING_H
#define MAIN_PROGRAM_MESSAGE_STARTING_H

#include <ros/service_traits.h>


#include <main_program/startingRequest.h>
#include <main_program/startingResponse.h>


namespace main_program
{

struct starting
{

typedef startingRequest Request;
typedef startingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct starting
} // namespace main_program


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main_program::starting > {
  static const char* value()
  {
    return "8e6928b31eac7bd32f54443af440aaac";
  }

  static const char* value(const ::main_program::starting&) { return value(); }
};

template<>
struct DataType< ::main_program::starting > {
  static const char* value()
  {
    return "main_program/starting";
  }

  static const char* value(const ::main_program::starting&) { return value(); }
};


// service_traits::MD5Sum< ::main_program::startingRequest> should match
// service_traits::MD5Sum< ::main_program::starting >
template<>
struct MD5Sum< ::main_program::startingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main_program::starting >::value();
  }
  static const char* value(const ::main_program::startingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_program::startingRequest> should match
// service_traits::DataType< ::main_program::starting >
template<>
struct DataType< ::main_program::startingRequest>
{
  static const char* value()
  {
    return DataType< ::main_program::starting >::value();
  }
  static const char* value(const ::main_program::startingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main_program::startingResponse> should match
// service_traits::MD5Sum< ::main_program::starting >
template<>
struct MD5Sum< ::main_program::startingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main_program::starting >::value();
  }
  static const char* value(const ::main_program::startingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_program::startingResponse> should match
// service_traits::DataType< ::main_program::starting >
template<>
struct DataType< ::main_program::startingResponse>
{
  static const char* value()
  {
    return DataType< ::main_program::starting >::value();
  }
  static const char* value(const ::main_program::startingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN_PROGRAM_MESSAGE_STARTING_H
